name: Build
on: 
  push:
    branches: [ "feature-*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3      
      - name: build
        run: echo Hello, world!
