name: Build
on: 
  push:
    branches: [ "feature-*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      - name: code checkout      
        uses: actions/checkout@v3
      - name: setup dotnet core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Build code
        run: dotnet build


